AdminJS.UserComponents = {};
AdminJS.env.ADMIN_RS_HOST = "http://localhost:8050";
import RejectSubmission from "../src/components/reject-submission";
AdminJS.UserComponents.RejectSubmission = RejectSubmission;
import RequireUpdate from "../src/components/require-update";
AdminJS.UserComponents.RequireUpdate = RequireUpdate;
import Dashboard from "../src/components/dashboard";
AdminJS.UserComponents.Dashboard = Dashboard;
import Show from "../src/components/status/show";
AdminJS.UserComponents.Show = Show;
import List from "../src/components/status/list";
AdminJS.UserComponents.List = List;
import ProjectSector from "../src/components/project-sector";
AdminJS.UserComponents.ProjectSector = ProjectSector;
import UrlPropery from "../src/components/url-property";
AdminJS.UserComponents.UrlPropery = UrlPropery;
import ImagePropery from "../src/components/image-property";
AdminJS.UserComponents.ImagePropery = ImagePropery;
import ChainIdSelect from "../src/components/chain-id/select";
AdminJS.UserComponents.ChainIdSelect = ChainIdSelect;
import ChainIdList from "../src/components/chain-id/list";
AdminJS.UserComponents.ChainIdList = ChainIdList;
import ChainIdShow from "../src/components/chain-id/show";
AdminJS.UserComponents.ChainIdShow = ChainIdShow;
import ChainIdFilter from "../src/components/chain-id/filter";
AdminJS.UserComponents.ChainIdFilter = ChainIdFilter;
