//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod prelude;

pub mod rejected_submissions;
pub mod sea_orm_active_enums;
pub mod submissions;
pub mod users;
pub mod users_chains;
pub mod waiting_for_update_submissions;
