//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::{
    rejected_submissions::Entity as RejectedSubmissions, submissions::Entity as Submissions,
    users::Entity as Users, users_chains::Entity as UsersChains,
    waiting_for_update_submissions::Entity as WaitingForUpdateSubmissions,
};
