//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "submission_status")]
pub enum SubmissionStatus {
    #[sea_orm(string_value = "approved")]
    Approved,
    #[sea_orm(string_value = "in_process")]
    InProcess,
    #[sea_orm(string_value = "rejected")]
    Rejected,
    #[sea_orm(string_value = "waiting_for_update")]
    WaitingForUpdate,
}
