//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub created_at: DateTime,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub is_superuser: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_chains::Entity")]
    UsersChains,
}

impl Related<super::users_chains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersChains.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
